# Generated by Django 3.1.2 on 2021-10-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0002_remove_image_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
    ]
