# Generated by Django 3.1.2 on 2021-10-17 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerspecs',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='part4.cart'),
        ),
        migrations.AlterField(
            model_name='computerspecs',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='part4.order'),
        ),
    ]
