# Generated by Django 3.1.2 on 2021-10-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0003_auto_20211017_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerspecs',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
