# Generated by Django 3.1.2 on 2021-10-17 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0005_auto_20211017_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='default',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='order',
        ),
        migrations.RemoveField(
            model_name='display',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='display',
            name='default',
        ),
        migrations.RemoveField(
            model_name='display',
            name='order',
        ),
        migrations.RemoveField(
            model_name='graphicscard',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='graphicscard',
            name='default',
        ),
        migrations.RemoveField(
            model_name='graphicscard',
            name='order',
        ),
        migrations.RemoveField(
            model_name='harddrive',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='harddrive',
            name='default',
        ),
        migrations.RemoveField(
            model_name='harddrive',
            name='order',
        ),
        migrations.RemoveField(
            model_name='os',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='os',
            name='default',
        ),
        migrations.RemoveField(
            model_name='os',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='default',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='order',
        ),
        migrations.RemoveField(
            model_name='soundcard',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='soundcard',
            name='default',
        ),
        migrations.RemoveField(
            model_name='soundcard',
            name='order',
        ),
        migrations.AddField(
            model_name='computer',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='part4.cart'),
        ),
        migrations.AddField(
            model_name='computer',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computer',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='part4.order'),
        ),
    ]
