# Generated by Django 3.1.2 on 2021-10-17 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0008_auto_20211017_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeuser',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='storeuser',
            name='orders',
        ),
        migrations.AddField(
            model_name='cart',
            name='store_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='part4.storeuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='store_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='part4.storeuser'),
            preserve_default=False,
        ),
    ]
