# Generated by Django 3.1.2 on 2021-10-17 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0009_auto_20211017_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerspecs',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='part4.computer'),
        ),
    ]
